[package]
name = "project-actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
jsonwebtoken = "9.3.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
